package com.soloretreat.ui.integration

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.soloretreat.data.local.entity.RetreatConfig
import com.soloretreat.data.repository.MealLogRepository
import com.soloretreat.data.repository.MeditationSessionRepository
import com.soloretreat.data.repository.PreceptRepository
import com.soloretreat.data.repository.RetreatRepository
import com.soloretreat.util.TimeUtils
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.launch
import java.time.LocalTime
import javax.inject.Inject

@HiltViewModel
class RetreatSummaryViewModel @Inject constructor(
    private val retreatRepository: RetreatRepository,
    private val meditationSessionRepository: MeditationSessionRepository,
    private val preceptRepository: PreceptRepository,
    private val mealLogRepository: MealLogRepository
) : ViewModel() {

    data class SummaryState(
        val config: RetreatConfig? = null,
        val totalMeditationMinutes: Long = 0,
        val formattedMeditationTime: String = "0m",
        val completedSessions: Int = 0,
        val interruptedSessions: Int = 0,
        val preceptRate: Float = 0f,
        val onTimeMeals: Int = 0,
        val lateMeals: Int = 0,
        val isLoading: Boolean = true
    )

    private val _state = MutableStateFlow(SummaryState())
    val state: StateFlow<SummaryState> = _state.asStateFlow()

    init {
        viewModelScope.launch {
            val config = retreatRepository.getConfig().firstOrNull()
            _state.value = _state.value.copy(config = config)

            if (config != null) {
                val startDate = config.startDate
                val endDate = config.endDate

                if (startDate != null && endDate != null) {
                    val startInstant = TimeUtils.localDateTimeToInstant(startDate, LocalTime.MIN)
                    val endInstant = TimeUtils.localDateTimeToInstant(endDate.plusDays(1), LocalTime.MIN)

                    val totalMinutes = meditationSessionRepository.getTotalMinutes(startInstant, endInstant)
                    val completed = meditationSessionRepository.countCompletedSessions(startInstant, endInstant)
                    val interrupted = meditationSessionRepository.countInterruptedSessions(startInstant, endInstant)
                    val preceptRate = preceptRepository.getObservanceRate(startDate, endDate)
                    val onTime = mealLogRepository.countOnTimeMeals(startDate, endDate)
                    val late = mealLogRepository.countLateMeals(startDate, endDate)

                    _state.value = SummaryState(
                        config = config,
                        totalMeditationMinutes = totalMinutes,
                        formattedMeditationTime = TimeUtils.formatDuration(totalMinutes),
                        completedSessions = completed,
                        interruptedSessions = interrupted,
                        preceptRate = preceptRate,
                        onTimeMeals = onTime,
                        lateMeals = late,
                        isLoading = false
                    )
                }
            }
        }
    }

    fun generateExportText(): String {
        val s = _state.value
        val config = s.config ?: return ""
        val startDate = config.startDate?.let { TimeUtils.formatFullDate(it) } ?: "?"
        val endDate = config.endDate?.let { TimeUtils.formatFullDate(it) } ?: "?"

        return buildString {
            appendLine("SOLO RETREAT SUMMARY")
            appendLine("====================")
            appendLine()
            appendLine("Dates: $startDate to $endDate")
            appendLine()
            appendLine("MEDITATION")
            appendLine("  Total time: ${s.formattedMeditationTime}")
            appendLine("  Completed sessions: ${s.completedSessions}")
            appendLine("  Interrupted sessions: ${s.interruptedSessions}")
            appendLine()
            appendLine("PRECEPTS")
            appendLine("  Average observance: ${(s.preceptRate * 100).toInt()}%")
            appendLine()
            appendLine("MEALS")
            appendLine("  Before noon: ${s.onTimeMeals}")
            appendLine("  After noon: ${s.lateMeals}")
            appendLine()
            appendLine("Generated by Solo Retreat Planner")
        }
    }
}